
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hivipgycifvbesazqghw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpdmlwZ3ljaWZ2YmVzYXpxZ2h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjM3NTk2NDAsImV4cCI6MjAzOTMzNTY0MH0.FmaomojUwXKJGe2bEc4lNNbnfm7rV97l1K1OiBY8_7A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Create storage bucket for images if it doesn't exist yet
(async () => {
  try {
    // Check if the images bucket exists
    const { data: buckets } = await supabase.storage.listBuckets();
    const imagesBucketExists = buckets?.some(bucket => bucket.name === 'images');
    
    // If the images bucket doesn't exist, create it
    if (!imagesBucketExists) {
      const { error } = await supabase.storage.createBucket('images', {
        public: true,
        fileSizeLimit: 10485760, // 10MB
      });
      
      if (error) {
        console.error('Error creating images bucket:', error);
      } else {
        console.log('Images bucket created successfully');
      }
    }
  } catch (error) {
    console.error('Error checking/creating storage bucket:', error);
  }
})();
